source 'https://github.com/ietstudio/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GamePluginIOS_Example', :exclusive => true do
  pod "GamePluginIOS", :path => "../"
end

target 'GamePluginIOS_Tests', :exclusive => true do
  pod "GamePluginIOS", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
